# Generated by Django 5.2.5 on 2026-08-05 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='due',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='ease',
            field=models.FloatField(default=2.5),
        ),
        migrations.AddField(
            model_name='card',
            name='interval',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='card',
            name='lapses',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='card',
            name='last_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='reps',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='card',
            name='srs_algorithm',
            field=models.CharField(choices=[('fsrs', 'FSRS'), ('sm2', 'SM-2'), ('anki', 'Anki')], default='fsrs', max_length=8),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 'Again'), (2, 'Hard'), (3, 'Good'), (4, 'Easy')])),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('time_ms', models.PositiveIntegerField(default=0)),
                ('feedback_text', models.TextField(blank=True, default='')),
                ('feedback_source', models.CharField(blank=True, default='', help_text="Where the feedback came from (e.g. 'ai:feedback', 'heuristic').", max_length=16)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='flashcards.card')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reviewed_at'],
                'indexes': [models.Index(fields=['card', '-reviewed_at'], name='flashcards__card_id_01abbd_idx'), models.Index(fields=['user', '-reviewed_at'], name='flashcards__user_id_6450f2_idx')],
            },
        ),
    ]
