# Generated by Django 5.2.5 on 2026-08-06 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Embedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('card', 'Card'), ('deck', 'Deck')], max_length=8)),
                ('entity_id', models.PositiveIntegerField()),
                ('vector', models.JSONField()),
                ('model', models.CharField(default='', max_length=64)),
                ('version', models.CharField(default='', max_length=16)),
                ('dim', models.PositiveIntegerField(default=1536)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='ai_embeddin_entity__1d4026_idx'), models.Index(fields=['model', 'version'], name='ai_embeddin_model_311a62_idx')],
                'constraints': [models.UniqueConstraint(fields=('entity_type', 'entity_id', 'model', 'version'), name='unique_embedding_per_entity_model_version')],
            },
        ),
    ]
